<?php

require 'bin/fpdf/fpdf.php';

/**
 * PDF Export for an Project Proposal
 *
 * @author Lukas Adler
 */
class pm_pdfcreator extends FPDF {

    private $o_fpdf;
    private $o_project;

    /**
     * Constructor 
     * @param int Project Proposal ID
     */
    public function __construct($i_ppID) {
        $this->o_fpdf = new FPDF();
        $this->o_fpdf->SetTitle("Projektantrag");
        $this->o_fpdf->SetAuthor("Autogenerated by PAMS");
        $this->o_fpdf->AddPage();

        $this->o_project = core()->db()->select("select p.*, a.a_name, a.s_id, s.s_name from projekt p "
                . "left join abteilung a on a.id = p.a_id "
                . "left join standort s on s.id = a.s_id where p.id = " . $i_ppID, "fetch");

        $this->setImage();
        $this->pdfHeadline();
        $this->pdfContent();
    }

    /**
     * Sets the Headline
     * @param type $this->o_fpdf
     * @param type $this->o_project
     */
    private function pdfHeadline() {
        //FONT Einstellung
        $this->o_fpdf->SetTextColor(0, 128, 128);
        $this->o_fpdf->SetFont('Arial', 'B', 18);
        $this->o_fpdf->Text(10, 148, $this->o_project->titel);
    }

    private function pdfContent() {
        //Start Datum
        $this->o_fpdf->SetTextColor(0, 128, 128);
        $this->o_fpdf->SetFont('Arial', 'B', 14);
        $this->o_fpdf->Text(10, 160, '| Startdatum');
        $this->o_fpdf->SetTextColor(0, 0, 0);
        $this->o_fpdf->SetFont('Arial', '', 12);
        $this->o_fpdf->Text(10, 165, $this->o_project->vor_sta_term);

        //Enddatum
        $this->o_fpdf->SetTextColor(0, 128, 128);
        $this->o_fpdf->SetFont('Arial', 'B', 14);
        $this->o_fpdf->Text(90, 160, '| Enddatum');
        $this->o_fpdf->SetTextColor(0, 0, 0);
        $this->o_fpdf->SetFont('Arial', '', 12);
        $this->o_fpdf->Text(90, 165, $this->o_project->vor_end_term);

        //Kurzbeschreibung
        $this->o_fpdf->SetTextColor(0, 128, 128);
        $this->o_fpdf->SetFont('Arial', 'B', 14);
        $this->o_fpdf->Text(10, 175, '| Kurzbeschreibung');
        $this->o_fpdf->SetTextColor(0, 0, 0);
        $this->o_fpdf->SetFont('Arial', '', 12);
        $this->o_fpdf->Text(10, 180, $this->o_project->beschreibung);

        //Rahmenbedinungen
        $this->o_fpdf->SetTextColor(0, 128, 128);
        $this->o_fpdf->SetFont('Arial', 'B', 14);
        $this->o_fpdf->Text(10, 190, '| Rahmenbedingungen');
        $this->o_fpdf->SetTextColor(0, 0, 0);
        $this->o_fpdf->SetFont('Arial', '', 12);
        $this->o_fpdf->Text(10, 195, $this->o_project->rahmbeding);

        //Kommunikationskonzept
        $this->o_fpdf->SetTextColor(0, 128, 128);
        $this->o_fpdf->SetFont('Arial', 'B', 14);
        $this->o_fpdf->Text(10, 205, '| Kommunikationskonzept');
        $this->o_fpdf->SetTextColor(0, 0, 0);
        $this->o_fpdf->SetFont('Arial', '', 12);
        $this->o_fpdf->Text(10, 210, $this->o_project->komm_konz);

        //Kreuzzielmethode
        $this->o_fpdf->SetTextColor(0, 128, 128);
        $this->o_fpdf->SetFont('Arial', 'B', 14);
        $this->o_fpdf->Text(10, 220, '| Kreuzzielmethode');

        $this->o_fpdf->SetTextColor(0, 128, 128);
        $this->o_fpdf->SetFont('Arial', '', 12);
        $this->o_fpdf->Text(10, 225, '| Wozu?');
        $this->o_fpdf->SetTextColor(0, 0, 0);
        $this->o_fpdf->SetFont('Arial', '', 12);
        $this->o_fpdf->Text(10, 230, $this->o_project->p_ziel1);

        $this->o_fpdf->SetTextColor(0, 128, 128);
        $this->o_fpdf->SetFont('Arial', '', 12);
        $this->o_fpdf->Text(90, 225, '| Was?');
        $this->o_fpdf->SetTextColor(0, 0, 0);
        $this->o_fpdf->SetFont('Arial', '', 12);
        $this->o_fpdf->Text(90, 230, $this->o_project->p_ziel2);

        $this->o_fpdf->SetTextColor(0, 128, 128);
        $this->o_fpdf->SetFont('Arial', '', 12);
        $this->o_fpdf->Text(10, 240, '| Wie gut?');
        $this->o_fpdf->SetTextColor(0, 0, 0);
        $this->o_fpdf->SetFont('Arial', '', 12);
        $this->o_fpdf->Text(10, 245, $this->o_project->p_ziel3);

        $this->o_fpdf->SetTextColor(0, 128, 128);
        $this->o_fpdf->SetFont('Arial', '', 12);
        $this->o_fpdf->Text(90, 240, '| Wen?');
        $this->o_fpdf->SetTextColor(0, 0, 0);
        $this->o_fpdf->SetFont('Arial', '', 12);
        $this->o_fpdf->Text(90, 245, $this->o_project->p_ziel4);
    }

    /**
     * Sets a Header Image to the PDF
     * @param fpdf-Object $this->o_fpdf
     */
    private function setImage() {
        $this->o_fpdf->Image('bin/custom/images/projekt_2.jpg', 0, 0, 210, 130, 'jpg');
    }

    public function createPdf() {
        $this->o_fpdf->Output();
    }

}
