<?php

define('FPDF_FONTPATH', 'bin\fpdf\font');
require 'bin/fpdf/fpdf.php';

/**
 * PDF Export for an Project Proposal
 *
 * @author Lukas Adler
 */
class pm_pdfcreator extends FPDF {

    private $o_fpdf;
    private $o_project;
    private $i_ppID;

    /**
     * Constructor 
     * @param int Project Proposal ID
     */
    public function __construct($i_ppID) {
        $this->o_fpdf = new FPDF();
        $this->o_fpdf->SetTitle("Projektantrag");
        $this->o_fpdf->SetAuthor("Autogenerated by PAMS");
        $this->o_fpdf->AddPage();
        $this->i_ppID = $i_ppID;

        $this->o_project = new pm_projekt();
        $this->o_project->load($i_ppID);

        $this->o_project = new pm_projekt();
        $this->o_project->load($i_ppID);



        $this->setImage();
        $this->pdfHeadline();
        $this->pdfNormalContent();
        $this->pdfStatsContent();
        $this->pdfMilestoneContent();
    }

    /**
     * Sets the Headline
     * @param type $this->o_fpdf
     * @param type $this->o_project
     */
    private function pdfHeadline() {
        //FONT Einstellung
        $this->o_fpdf->SetTextColor(0, 128, 128);
        $this->o_fpdf->SetFont('Arial', 'B', 18);
        $this->o_fpdf->Text(10, 148, utf8_decode($this->o_project->getTitle()));
        $this->o_fpdf->Text(10, 151, "________________________________________________________________");
    }

    /**
     * Adds the Basic Content to the PDF
     */
    private function pdfNormalContent() {
        //Start Datum
        $this->o_fpdf->SetTextColor(0, 128, 128);
        $this->o_fpdf->SetFont('Arial', 'B', 14);
        $this->o_fpdf->Text(10, 160, '| Startdatum');
        $this->o_fpdf->SetTextColor(0, 0, 0);
        $this->o_fpdf->SetFont('Arial', '', 12);
        $this->o_fpdf->Text(10, 167, utf8_decode($this->o_project->getExpectedStartTime()));

        //Enddatum
        $this->o_fpdf->SetTextColor(0, 128, 128);
        $this->o_fpdf->SetFont('Arial', 'B', 14);
        $this->o_fpdf->Text(90, 160, '| Enddatum');
        $this->o_fpdf->SetTextColor(0, 0, 0);
        $this->o_fpdf->SetFont('Arial', '', 12);
        $this->o_fpdf->Text(90, 167, utf8_decode($this->o_project->getExpectedEndTime()));

        //Kurzbeschreibung
        $this->o_fpdf->SetTextColor(0, 128, 128);
        $this->o_fpdf->SetFont('Arial', 'B', 14);
        $this->o_fpdf->Text(10, 178, '| Kurzbeschreibung');
        $this->o_fpdf->SetTextColor(0, 0, 0);
        $this->o_fpdf->SetFont('Arial', '', 12);
        $this->o_fpdf->Text(10, 184, utf8_decode($this->o_project->getDescription()));

        //Rahmenbedinungen
        $this->o_fpdf->SetTextColor(0, 128, 128);
        $this->o_fpdf->SetFont('Arial', 'B', 14);
        $this->o_fpdf->Text(10, 195, '| Rahmenbedingungen');
        $this->o_fpdf->SetTextColor(0, 0, 0);
        $this->o_fpdf->SetFont('Arial', '', 12);
        $this->o_fpdf->Text(10, 202, utf8_decode($this->o_project->getGeneralConditions()));

        //Kommunikationskonzept
        $this->o_fpdf->SetTextColor(0, 128, 128);
        $this->o_fpdf->SetFont('Arial', 'B', 14);
        $this->o_fpdf->Text(10, 213, '| Kommunikationskonzept');
        $this->o_fpdf->SetTextColor(0, 0, 0);
        $this->o_fpdf->SetFont('Arial', '', 12);
        $this->o_fpdf->Text(10, 220, utf8_decode($this->o_project->getCommunicationConcept()));

        //Kreuzzielmethode
        $this->o_fpdf->SetTextColor(0, 128, 128);
        $this->o_fpdf->SetFont('Arial', 'B', 14);
        $this->o_fpdf->Text(10, 231, '| Kreuzzielmethode');

        $this->o_fpdf->SetTextColor(0, 128, 128);
        $this->o_fpdf->SetFont('Arial', '', 12);
        $this->o_fpdf->Text(10, 236, '| Wozu?');
        $this->o_fpdf->SetTextColor(0, 0, 0);
        $this->o_fpdf->SetFont('Arial', '', 12);
        $this->o_fpdf->Text(10, 243, utf8_decode($this->o_project->getTargetCross1()));

        $this->o_fpdf->SetTextColor(0, 128, 128);
        $this->o_fpdf->SetFont('Arial', '', 12);
        $this->o_fpdf->Text(90, 236, '| Was?');
        $this->o_fpdf->SetTextColor(0, 0, 0);
        $this->o_fpdf->SetFont('Arial', '', 12);
        $this->o_fpdf->Text(90, 243, utf8_decode($this->o_project->getTargetCross2()));

        $this->o_fpdf->SetTextColor(0, 128, 128);
        $this->o_fpdf->SetFont('Arial', '', 12);
        $this->o_fpdf->Text(10, 253, '| Wie gut?');
        $this->o_fpdf->SetTextColor(0, 0, 0);
        $this->o_fpdf->SetFont('Arial', '', 12);
        $this->o_fpdf->Text(10, 260, utf8_decode($this->o_project->getTargetCross3()));

        $this->o_fpdf->SetTextColor(0, 128, 128);
        $this->o_fpdf->SetFont('Arial', '', 12);
        $this->o_fpdf->Text(90, 253, '| Wen?');
        $this->o_fpdf->SetTextColor(0, 0, 0);
        $this->o_fpdf->SetFont('Arial', '', 12);
        $this->o_fpdf->Text(90, 260, utf8_decode($this->o_project->getTargetCross4()));
    }

    /**
     * Adds a New Page + Stats and other Key Values to the PDF
     */
    private function pdfStatsContent() {
        $this->o_fpdf->AddPage();

        //HEADLINE
        $this->o_fpdf->SetTextColor(0, 128, 128);
        $this->o_fpdf->SetFont('Arial', 'B', 18);
        $this->o_fpdf->Text(10, 20, "Kennzahlen");
        $this->o_fpdf->Text(10, 23, "________________________________________________________________");


        //Monetäre Kosten
        $this->o_fpdf->SetTextColor(0, 128, 128);
        $this->o_fpdf->SetFont('Arial', 'B', 14);
        $this->o_fpdf->Text(10, 35, utf8_decode('| Monetäre Kosten'));
        $this->o_fpdf->SetTextColor(0, 0, 0);
        $this->o_fpdf->SetFont('Arial', '', 12);
        $this->o_fpdf->Text(10, 42, utf8_decode($this->o_project->getMoneyCosts()));

        //Monetärer Nutzen
        $this->o_fpdf->SetTextColor(0, 128, 128);
        $this->o_fpdf->SetFont('Arial', 'B', 14);
        $this->o_fpdf->Text(90, 35, utf8_decode('| Monetärer Nutzen'));
        $this->o_fpdf->SetTextColor(0, 0, 0);
        $this->o_fpdf->SetFont('Arial', '', 12);
        $this->o_fpdf->Text(90, 42, utf8_decode($this->o_project->getMonesEarnings()));

        //Kapitalwert
        $this->o_fpdf->SetTextColor(0, 128, 128);
        $this->o_fpdf->SetFont('Arial', 'B', 14);
        $this->o_fpdf->Text(10, 53, utf8_decode('| Kapitalwertmethode'));
        $this->o_fpdf->SetTextColor(0, 0, 0);
        $this->o_fpdf->SetFont('Arial', '', 12);


        $this->capitalFlowTable(array("Jahr", "Kosten", "Nutzen"), $this->o_project->getCapitalflow());
    }

    /**
     * Table Creator for the Capital Flow Method
     * @param array $header
     * @param CapitalFlow $data
     */
    private function capitalFlowTable($header, $data) {
        $this->o_fpdf->SetX(10);
        $this->o_fpdf->SetY(60);

        // Column widths
        $w = array(60, 60, 60);
        // Header
        for ($i = 0; $i < count($header); $i++)
            $this->o_fpdf->Cell($w[$i], 7, $header[$i], 1, 0, 'C');
        $this->o_fpdf->Ln();
        // Data
        foreach ($data as $row) {
            $this->o_fpdf->Cell($w[0], 6, $row->getYear(), 'LR');
            $this->o_fpdf->Cell($w[1], 6, $row->getInputMoneyVal(), 'LR', 0, 'R');
            $this->o_fpdf->Cell($w[2], 6, $row->getOutputMoneyVal(), 'LR', 0, 'R');
            $this->o_fpdf->Ln();
        }
        // Closure line
        $this->o_fpdf->Cell(array_sum($w), 0, '', 'T');
    }

    /**
     * Adds the Milestones to the PDF
     */
    private function pdfMilestoneContent() {
        $this->o_fpdf->AddPage();

        //HEADLINE
        $this->o_fpdf->SetTextColor(0, 128, 128);
        $this->o_fpdf->SetFont('Arial', 'B', 18);
        $this->o_fpdf->Text(10, 20, "Meilensteine");
        $this->o_fpdf->Text(10, 23, "________________________________________________________________");


        $this->o_fpdf->SetTextColor(0, 0, 0);
        $this->o_fpdf->SetFont('Arial', '', 12);
        $this->milestoneTable(array("MeilensteinNr", "Meilensteinname", "Erledigt"), $this->o_project->getMilestones());
    }

    /**
     * Prints the Milestones to the Table
     * @param type $header
     * @param type $data
     */
    private function milestoneTable($header, $data) {
        $this->o_fpdf->SetX(10);
        $this->o_fpdf->SetY(30);

        // Column widths
        $w = array(60, 60, 60);
        // Header
        for ($i = 0; $i < count($header); $i++)
            $this->o_fpdf->Cell($w[$i], 7, $header[$i], 1, 0, 'C');
        $this->o_fpdf->Ln();
        // Data
        foreach ($data as $row) {
            $this->o_fpdf->Cell($w[0], 6, $row->getMilestoneNr(), 'LR');
            $this->o_fpdf->Cell($w[1], 6, $row->getMilestoneName(), 'LR', 0, 'R');
            $this->o_fpdf->Cell($w[2], 6, $this->boolConverter($row->getFinished()), 'LR', 0, 'R');
            $this->o_fpdf->Ln();
        }
        // Closure line
        $this->o_fpdf->Cell(array_sum($w), 0, '', 'T');
    }

    /**
     * Sets a Header Image to the PDF
     * @param fpdf-Object $this->o_fpdf
     */
    private function setImage() {
        $this->o_fpdf->Image(substr(core()->randomPic()->getPicture($this->i_ppID, "projekt"), 4), 0, 0, 210, 130, 'jpg');
    }

    /**
     * Creats the PDF
     */
    public function createPdf() {
        $this->o_fpdf->Output();
    }

    private function boolConverter($bool) {
        return ($bool = true) ? "Ja" : "Nein";
    }

}
