CREATE TABLE IF NOT EXISTS Users (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(30) NOT NULL,
passwort VARCHAR(30) NOT NULL,
reg_date TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Mitarbeiter (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
users_id INT(6) UNSIGNED,
FOREIGN KEY (users_id) REFERENCES Users(id),
nachname VARCHAR(30) NOT NULL,
vorname VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS Berechtigung (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
berechtigung VARCHAR(30) UNIQUE
);

CREATE TABLE IF NOT EXISTS Mitberecht (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
m_id INT(6) UNSIGNED,
FOREIGN KEY (m_id) REFERENCES Mitarbeiter(id),
b_id INT(6) UNSIGNED,
FOREIGN KEY (b_id) REFERENCES Berechtigung(id)
);

CREATE TABLE IF NOT EXISTS Firma (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS Ort (
plz INT(10) UNSIGNED PRIMARY KEY,
ort VARCHAR(30) NOT NULL,
land VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS Standort (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(30) NOT NULL,
plz INT(10) UNSIGNED,
FOREIGN KEY (plz) REFERENCES Ort(plz),
strasse VARCHAR(30) NOT NULL,
hausnummer VARCHAR(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS Bereich (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
s_id INT(6) UNSIGNED,
FOREIGN KEY (s_id) REFERENCES Standort(id),
name VARCHAR(30) NOT NULL,
anzMit INT(10) UNSIGNED,
budget INT(20) NOT NULL
);



