CREATE TABLE IF NOT EXISTS Users(
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(30) NOT NULL,
  passwort VARCHAR(40) NOT NULL,
  reg_datum TIMESTAMP
);
CREATE TABLE IF NOT EXISTS Mitarbeiter(
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  u_id INT(6) UNSIGNED,
  FOREIGN KEY(users_id) REFERENCES Users(id),
  nachname VARCHAR(30) NOT NULL,
  vorname VARCHAR(30) NOT NULL
);
CREATE TABLE IF NOT EXISTS Berechtigung(
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  berechtigung VARCHAR(30) UNIQUE
);
CREATE TABLE IF NOT EXISTS Mitberecht(
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  m_id INT(6) UNSIGNED,
  FOREIGN KEY(m_id) REFERENCES Mitarbeiter(id),
  b_id INT(6) UNSIGNED,
  FOREIGN KEY(b_id) REFERENCES Berechtigung(id)
);
CREATE TABLE IF NOT EXISTS Firma(
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(50) NOT NULL
);
CREATE TABLE IF NOT EXISTS Ort(
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  plz INT(10) UNSIGNED,
  ort VARCHAR(30) NOT NULL
);
CREATE TABLE IF NOT EXISTS Standort(
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(30) NOT NULL,
  plz_id INT(6) UNSIGNED,
  FOREIGN KEY(plz_id) REFERENCES Ort(id),
  strasse VARCHAR(30) NOT NULL,
  hausnummer VARCHAR(6) NOT NULL
);
CREATE TABLE IF NOT EXISTS Bereich(
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  s_id INT(6) UNSIGNED,
  FOREIGN KEY(s_id) REFERENCES Standort(id),
  b_name VARCHAR(30) NOT NULL,
  anz_mit INT(10) UNSIGNED,
  budget INT(20) NOT NULL
);
CREATE TABLE IF NOT EXISTS Abteilung(
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  b_id INT(6) UNSIGNED,
  FOREIGN KEY(b_id) REFERENCES Bereich(id),
  a_name VARCHAR(30) NOT NULL,
  anz_Mit INT(10) UNSIGNED,
  budget INT(20) NOT NULL
);
CREATE TABLE IF NOT EXISTS AbtLeit(
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  m_id INT(6) UNSIGNED NOT NULL,
  a_id INT(6) UNSIGNED NOT NULL,
  FOREIGN KEY(m_id) REFERENCES Mitarbeiter(id),
  FOREIGN KEY(a_id) REFERENCES Abteilung(id)
);
CREATE TABLE IF NOT EXISTS BerLeit(
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  m_id INT(6) UNSIGNED NOT NULL,
  b_id INT(6) UNSIGNED NOT NULL,
  FOREIGN KEY(m_id) REFERENCES Mitarbeiter(id),
  FOREIGN KEY(b_id) REFERENCES Bereich(id)
);
CREATE TABLE IF NOT EXISTS AbtMitarb(
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  m_id INT(6) UNSIGNED NOT NULL,
  FOREIGN KEY(m_id) REFERENCES Mitarbeiter(id),
  a_id INT(6) UNSIGNED NOT NULL,
  FOREIGN KEY(a_id) REFERENCES Abteilung(id)
);
CREATE TABLE IF NOT EXISTS BerMitarb(
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  m_id INT(6) UNSIGNED NOT NULL,
  FOREIGN KEY(m_id) REFERENCES Mitarbeiter(id),
  a_id INT(6) UNSIGNED NOT NULL,
  FOREIGN KEY(a_id) REFERENCES Abteilung(id)
);
CREATE TABLE IF NOT EXISTS ProjStatus(
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  status VARCHAR(20) NOT NULL
);
CREATE TABLE IF NOT EXISTS Projekt(
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  titel VARCHAR(40) NOT NULL,
  e_id INT(6) NOT NULL,
  FOREIGN KEY(b_id) REFERENCES Mitarbeiter(id),
  b_id INT(6) NOT NULL,
  FOREIGN KEY(b_id) REFERENCES Bereich(id),
  erstell_datum TIMESTAMP,
  mitarb_anz INT(6),
  budget INT(20),
  vor_sta_term DATE,
  vor_end_term DATE,
  tat_sta_term DATE,
  tat_end_term DATE,
  beschreibung TEXT,
  nutzen VARCHAR(255)
);